#encoding=utf-8

'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

import time, mtools, math

def hexagonal(n):
    return n*(2*n-1)

'''
all hexagonal numbers are also triangle number.
H = h*(2h-1)
T = t*(t+1)/2
generating t by t=2h-1
'''
def is_tri(n):
    t = 1+8*n
    r = int(math.sqrt(t))
    if r*r == t:
        return (r-1)%2 == 0

def is_pen(n):
    t = 1+24*n
    r = int(math.sqrt(t))
    if r*r == t:
        return (r+1)%6 == 0

def solve():
    n = 144
    while True:
        h = hexagonal(n)
        if is_pen(h):
            return h
        n = n + 1

def test():
    t = [1, 3, 6, 10, 15]
    for x in t:
        assert is_tri(x)

    t = [1, 5, 12, 22, 35]
    for x in t:
        assert is_pen(x)

if __name__ == "__main__":
    test()
    t = time.time()
    print "answer = %s" % (solve())
    print "(%s)" % (time.time() - t)
